export const logTypes = {
  member_join: { label: "Member Join" },
  member_leave: { label: "Member Leave" },
  avatar_update: { label: "Avatar Update" },
  username_update: { label: "Username Update" },
  display_name_update: { label: "Display Name Update" },
  role_add: { label: "Role Added" },
  role_remove: { label: "Role Removed" },
  role_create: { label: "Role Created" },
  role_update: { label: "Role Updated" },
  role_delete: { label: "Role Deleted" },
  emoji_create: { label: "Emoji Created" },
  emoji_update: { label: "Emoji Updated" },
  emoji_delete: { label: "Emoji Deleted" },
  sticker_create: { label: "Sticker Created" },
  sticker_update: { label: "Sticker Updated" },
  sticker_delete: { label: "Sticker Deleted" },
  nickname_update: { label: "Nickname Update" },
  server_update: { label: "Server Update" },
  ban_add: { label: "Member Banned" },
  ban_remove: { label: "Member Unbanned" },
  invite_create: { label: "Invite Created" },
  invite_delete: { label: "Invite Deleted" },
} as const;

export type LogType = keyof typeof logTypes;
